version: "3.3"

services:
  redis:
    image: redis:latest
    command: bash -c "redis-server --appendonly yes"
    volumes:
      - ./cache:/data
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres